spring:
    datasource:
        url: jdbc:mysql://localhost:3306/web?characterEncoding=UTF-8&autoReconnect=true
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLInnoDBDialect
    application:
        name: backend
    content:
        fs:
            filesystem-root: "/pictures/backend/"
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
    web:
        resources:
            add-mappings: false
    mvc:
        throw-exception-if-no-handler-found: true
    redis:
        host: localhost
        port: 6379
        # 连接超时时间（记得添加单位，Duration）
        timeout: 10000ms
        # Redis默认情况下有16个分片，这里配置具体使用的分片
        # database: 0
        lettuce:
            pool:
                # 连接池最大连接数（使用负值表示没有限制） 默认 8
                max-active: 8
                # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
                max-wait: -1ms
                # 连接池中的最大空闲连接 默认 8
                max-idle: 8
                # 连接池中的最小空闲连接 默认 0
                min-idle: 0
    data:
        redis:
            repositories:
                enabled: false
jwt:
    config:
        key: isepweb
        ttl: 600000
        rememberTtl: 604800000
logging:
    level:
        com.isep.project: debug
#springdoc:
#    swagger-ui:
#        # 自定义的文档界面访问路径。默认访问路径是/swagger-ui.html
#        path: /springdoc/docs.html
#
#        # 字符串类型，一共三个值来控制操作和标记的默认展开设置。它可以是“list”（仅展开标记）、“full”（展开标记和操作）或“none”（不展开任何内容）。
#        docExpansion: none
#
#        # 布尔值。控制“试用”请求的请求持续时间（毫秒）的显示。
#        displayRequestDuration: true
#
#        # 布尔值。控制供应商扩展（x-）字段和操作、参数和架构值的显示。
#        showExtensions: true
#
#        # 布尔值。控制参数的扩展名（pattern、maxLength、minLength、maximum、minminimum）字段和值的显示。
#        showCommonExtensions: true
#
#        # 布尔值。禁用swagger用户界面默认petstore url。（从v1.4.1开始提供）。
#        disable-swagger-default-url: true
#
#    api-docs:
#        # enabled the /v3/api-docs endpoint
#        enabled: true
#
#        # 自定义的文档api元数据访问路径。默认访问路径是/v3/api-docs
#        path: /springdoc/api-docs
#
#        # 布尔值。在@Schema（名称name、标题title和说明description，三个属性）上启用属性解析程序。
#        resolve-schema-properties: true
#
#    # 布尔值。实现OpenApi规范的打印。
#    writer-with-default-pretty-printer: true
#
## ===== swagger配置 =====#
#swagger:
#    application-name: ${spring.application.name}
#    application-version: 1.0
#    application-description: backend of web project
#    try-host: http://localhost:${server.port}

server:
    port: 17698
debug: false

custom:
    ignores:
        post:
            - "/auth"
            - "/register"
        get:
            - "/v3/**"
            - "/swagger-ui.html"
            - "/swagger-ui/**"
            - "profile/**"
        delete:
            - "/auth"
        options:
            - "/**"
        pattern:
            - "/pictures/**"
        patch:
            - "/register"