spring:
    datasource:
        url: jdbc:mysql://localhost:3306/web?characterEncoding=UTF-8&autoReconnect=true
        username: root
        password: root
    jpa:
        hibernate:
            ddl-auto: update #自动更新
        show-sql: true  #日志中显示sql语句
    application:
        name: backend
server:
    port: 12546